FROM tomcat:9.0.64-jre8

RUN rm -rf /usr/local/tomcat/webapps/*

COPY ./target/ServaWeb.war /usr/local/tomcat/webapps/ROOT.war

# Install dependencies
RUN apt-get update && \
    apt-get install -y wget apt-transport-https software-properties-common

# Add Microsoft package signing key and repository
RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    rm packages-microsoft-prod.deb

# Install .NET SDK
RUN apt-get update && \
    apt-get install -y dotnet-sdk-6.0

# Clean up
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8080

CMD ["catalina.sh", "run"]

