FROM mysql:5.7

ENV MYSQL_ROOT_PASSWORD=abcd1234

COPY my.cnf /etc/mysql/conf.d/my.cnf
COPY initservamysql57.sql /docker-entrypoint-initdb.d/

EXPOSE 3306

VOLUME ["/var/lib/mysql"]

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["mysqld"]

